/* Generated By:JJTree: Do not edit this line. PatternOWLExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Pattern,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.coode.patterns.syntax;

public
class PatternOWLExpression extends SimpleNode {
  public PatternOWLExpression(int id) {
    super(id);
  }

  public PatternOWLExpression(PatternParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2dd686b3c2048814bfaba5c1a788ef82 (do not edit this line) */
