/* Generated By:JJTree: Do not edit this line. PatternClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Pattern,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.coode.patterns.syntax;

public
class PatternClause extends SimpleNode {
  public PatternClause(int id) {
    super(id);
  }

  public PatternClause(PatternParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=37e8b5a1390fa570bbd12dca0d39dc8c (do not edit this line) */
