/* Generated By:JJTree: Do not edit this line. PatternStart.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Pattern,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.coode.patterns.syntax;

public
class PatternStart extends SimpleNode {
  public PatternStart(int id) {
    super(id);
  }

  public PatternStart(PatternParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c8675d6a3128d3fe745a91517ce44a24 (do not edit this line) */
