/* Generated By:JJTree: Do not edit this line. PatternexpressionGeneratedVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Pattern,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.coode.patterns.syntax;

public
class PatternexpressionGeneratedVariable extends SimpleNode {
  public PatternexpressionGeneratedVariable(int id) {
    super(id);
  }

  public PatternexpressionGeneratedVariable(PatternParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4d5eedb71c91a5dc1320d0d2010ecb5d (do not edit this line) */
