/* Generated By:JJTree: Do not edit this line. PatternopplFunctionArgs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Pattern,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.coode.patterns.syntax;

public
class PatternopplFunctionArgs extends SimpleNode {
  public PatternopplFunctionArgs(int id) {
    super(id);
  }

  public PatternopplFunctionArgs(PatternParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=addf2ca4170cd01fa5bb3bece7a839d5 (do not edit this line) */
