/* Generated By:JavaCC: Do not edit this line. PatternParserTreeConstants.java Version 5.0 */
package org.coode.patterns.syntax;

public interface PatternParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTOPPLPATTERNSTATEMENT = 2;
  public int JJTRENDERING = 3;
  public int JJTSIMPLECALL = 4;
  public int JJTVARIABLEEXPRESSION = 5;
  public int JJTOPPLFUNCTIONARGS = 6;
  public int JJTEXPRESSIONGENERATEDVARIABLE = 7;
  public int JJTREGEXPOPERATION = 8;
  public int JJTREADSTRING = 9;
  public int JJTOWLEXPRESSION = 10;
  public int JJTCLAUSE = 11;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "OPPLPatternStatement",
    "Rendering",
    "simpleCall",
    "variableExpression",
    "opplFunctionArgs",
    "expressionGeneratedVariable",
    "regexpOperation",
    "readString",
    "OWLExpression",
    "Clause",
  };
}
/* JavaCC - OriginalChecksum=20ab58d212e8b0d11ca3116b6d306756 (do not edit this line) */
