/* Generated By:JJTree: Do not edit this line. PatternreadString.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Pattern,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.coode.patterns.syntax;

public
class PatternreadString extends SimpleNode {
  public PatternreadString(int id) {
    super(id);
  }

  public PatternreadString(PatternParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=635cb4f32e2649c3cd15b63e035ad919 (do not edit this line) */
