/* Generated By:JJTree: Do not edit this line. PatternRendering.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Pattern,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.coode.patterns.syntax;

public
class PatternRendering extends SimpleNode {
  public PatternRendering(int id) {
    super(id);
  }

  public PatternRendering(PatternParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2b032cbe75418841b70f0b55eda4db54 (do not edit this line) */
