/* Generated By:JJTree: Do not edit this line. PatternOPPLPatternStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Pattern,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.coode.patterns.syntax;

public
class PatternOPPLPatternStatement extends SimpleNode {
  public PatternOPPLPatternStatement(int id) {
    super(id);
  }

  public PatternOPPLPatternStatement(PatternParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e7523f656e049b638264bb08d43fd21c (do not edit this line) */
