/* Generated By:JJTree: Do not edit this line. PatternsimpleCall.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Pattern,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.coode.patterns.syntax;

public
class PatternsimpleCall extends SimpleNode {
  public PatternsimpleCall(int id) {
    super(id);
  }

  public PatternsimpleCall(PatternParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=837925d448ed8394ad91478f247e5d7e (do not edit this line) */
