/* Generated By:JavaCC: Do not edit this line. OPPLParserTreeConstants.java Version 5.0 */
package org.coode.oppl.syntax;

public interface OPPLParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPARSE = 1;
  public int JJTVOID = 2;
  public int JJTACTIONS = 3;
  public int JJTVARIABLEDEFINITION = 4;
  public int JJTEXPRESSIONGENERATEDVARIABLE = 5;
  public int JJTREGEXPOPERATION = 6;
  public int JJTREADSTRING = 7;
  public int JJTTYPESCOPE = 8;
  public int JJTPARSESCOPE = 9;
  public int JJTCONSTRAINT = 10;
  public int JJTMATCHCONSTRAINT = 11;
  public int JJTOWLEXPRESSION = 12;
  public int JJTQUERY = 13;
  public int JJTACTION = 14;
  public int JJTCLAUSE = 15;


  public String[] jjtNodeName = {
    "Start",
    "parse",
    "void",
    "Actions",
    "VariableDefinition",
    "expressionGeneratedVariable",
    "regexpOperation",
    "readString",
    "typeScope",
    "parseScope",
    "Constraint",
    "matchConstraint",
    "OWLExpression",
    "query",
    "Action",
    "Clause",
  };
}
/* JavaCC - OriginalChecksum=79d17f7b3796cbc0d69ce805af4b5f69 (do not edit this line) */
