/* Generated By:JavaCC: Do not edit this line. OPPLParserVisitor.java Version 5.0 */
package org.coode.oppl.syntax;

public interface OPPLParserVisitor {
	public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=c90f7760fe8df3c29eeaaceadefc9ee9 (do not edit this line) */
