package org.coode.oppl;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.io.StringDocumentSource;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyCreationException;
import org.semanticweb.owlapi.model.OWLOntologyManager;

public class Ontologies {
    private final static String test_owl = "<?xml version=\"1.0\"?>\n"
            + "\n"
            + "\n"
            + "<!DOCTYPE Ontology [\n"
            + "    <!ENTITY xsd \"http://www.w3.org/2001/XMLSchema#\" >\n"
            + "    <!ENTITY xml \"http://www.w3.org/XML/1998/namespace\" >\n"
            + "    <!ENTITY rdfs \"http://www.w3.org/2000/01/rdf-schema#\" >\n"
            + "    <!ENTITY rdf \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" >\n"
            + "]>\n"
            + "\n"
            + "\n"
            + "<Ontology xmlns=\"http://www.w3.org/2002/07/owl#\"\n"
            + "     xml:base=\"http://www.co-ode.org/roberts/country.owl\"\n"
            + "     xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
            + "     xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
            + "     xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
            + "     xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"\n"
            + "     ontologyIRI=\"http://www.co-ode.org/roberts/country.owl\">\n"
            + "    <Prefix name=\"xsd\" IRI=\"http://www.w3.org/2001/XMLSchema#\"/>\n"
            + "    <Prefix name=\"owl2xml\" IRI=\"http://www.w3.org/2006/12/owl2-xml#\"/>\n"
            + "    <Prefix name=\"owl\" IRI=\"http://www.w3.org/2002/07/owl#\"/>\n"
            + "    <Prefix name=\"\" IRI=\"http://www.w3.org/2006/12/owl2-xml#\"/>\n"
            + "    <Prefix name=\"rdf\" IRI=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"/>\n"
            + "    <Prefix name=\"rdfs\" IRI=\"http://www.w3.org/2000/01/rdf-schema#\"/>\n"
            + "    <Prefix name=\"country\" IRI=\"http://www.co-ode.org/roberts/country.owl#\"/>\n"
            + "    <Declaration><Class IRI=\"#Chunk\"/></Declaration>\n"
            + "    <Declaration><Class IRI=\"#Fragment\"/></Declaration>\n"
            + "    <Declaration><DataProperty IRI=\"#size\"/></Declaration>\n"
            + "    <Declaration><NamedIndividual IRI=\"#Asinara\"/></Declaration>\n"
            + "    <EquivalentClasses><Class IRI=\"#Chunk\"/><Class IRI=\"#Fragment\"/></EquivalentClasses>\n"
            + "    <SubClassOf><Class IRI=\"#BoundaryFragment\"/><Class IRI=\"#Fragment\"/></SubClassOf>\n"
            + "    <SubClassOf><Class IRI=\"#LandBoundaryFragment\"/><Class IRI=\"#BoundaryFragment\"/></SubClassOf>\n"
            + "    <SubClassOf><Class IRI=\"#WaterBoundaryFragment\"/><Class IRI=\"#BoundaryFragment\"/></SubClassOf>\n"
            + "    <ClassAssertion><Class IRI=\"#Country\"/><NamedIndividual IRI=\"#Asinara\"/></ClassAssertion>\n"
            + "    <SubObjectPropertyOf><ObjectProperty IRI=\"#hasLandBoundary\"/><ObjectProperty IRI=\"#hasBoundary\"/></SubObjectPropertyOf>\n"
            + "    <SubObjectPropertyOf><ObjectProperty IRI=\"#hasWaterBoundary\"/><ObjectProperty IRI=\"#hasBoundary\"/></SubObjectPropertyOf>\n"
            + "    <ObjectPropertyDomain><ObjectProperty IRI=\"#adjacentTo\"/><Class IRI=\"#Country\"/></ObjectPropertyDomain>\n"
            + "    <ObjectPropertyDomain><ObjectProperty IRI=\"#borders\"/><Class IRI=\"#Country\"/></ObjectPropertyDomain>\n"
            + "    <ObjectPropertyDomain><ObjectProperty IRI=\"#dependencyOf\"/><Class IRI=\"#Country\"/></ObjectPropertyDomain>\n"
            + "    <ObjectPropertyDomain><ObjectProperty IRI=\"#hasBoundary\"/><Class IRI=\"#Country\"/></ObjectPropertyDomain>\n"
            + "    <ObjectPropertyDomain><ObjectProperty IRI=\"#hasLandBoundary\"/><Class IRI=\"#Country\"/></ObjectPropertyDomain>\n"
            + "    <ObjectPropertyDomain><ObjectProperty IRI=\"#hasWaterBoundary\"/><Class IRI=\"#Country\"/></ObjectPropertyDomain>\n"
            + "    <ObjectPropertyRange><ObjectProperty IRI=\"#adjacentTo\"/><Class IRI=\"#Country\"/></ObjectPropertyRange>\n"
            + "    <ObjectPropertyRange><ObjectProperty IRI=\"#borders\"/><Class IRI=\"#Country\"/></ObjectPropertyRange>\n"
            + "    <ObjectPropertyRange><ObjectProperty IRI=\"#dependencyOf\"/><Class IRI=\"#Country\"/></ObjectPropertyRange>\n"
            + "    <ObjectPropertyRange><ObjectProperty IRI=\"#hasBoundary\"/><Class IRI=\"#BoundaryFragment\"/></ObjectPropertyRange>\n"
            + "    <ObjectPropertyRange><ObjectProperty IRI=\"#hasLandBoundary\"/><Class IRI=\"#LandBoundaryFragment\"/></ObjectPropertyRange>\n"
            + "    <ObjectPropertyRange><ObjectProperty IRI=\"#hasWaterBoundary\"/><Class IRI=\"#WaterBoundaryFragment\"/></ObjectPropertyRange>\n"
            + "    <DataPropertyRange><DataProperty IRI=\"#size\"/><Datatype abbreviatedIRI=\"xsd:int\"/></DataPropertyRange>\n"
            + "</Ontology>";
    private static final String naf_owl = "<?xml version=\"1.0\"?>\n"
            + "<!DOCTYPE rdf:RDF [\n"
            + "    <!ENTITY owl \"http://www.w3.org/2002/07/owl#\" >\n"
            + "    <!ENTITY xsd \"http://www.w3.org/2001/XMLSchema#\" >\n"
            + "    <!ENTITY owl2xml \"http://www.w3.org/2006/12/owl2-xml#\" >\n"
            + "    <!ENTITY rdfs \"http://www.w3.org/2000/01/rdf-schema#\" >\n"
            + "    <!ENTITY rdf \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" >\n"
            + "    <!ENTITY Ontology1278505688859 \"http://www.semanticweb.org/ontologies/2010/6/Ontology1278505688859.owl#\" >\n"
            + "]>\n"
            + "<rdf:RDF xmlns=\"http://www.semanticweb.org/ontologies/2010/6/Ontology1278505688859.owl#\"\n"
            + "     xml:base=\"http://www.semanticweb.org/ontologies/2010/6/Ontology1278505688859.owl\"\n"
            + "     xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
            + "     xmlns:owl2xml=\"http://www.w3.org/2006/12/owl2-xml#\"\n"
            + "     xmlns:Ontology1278505688859=\"http://www.semanticweb.org/ontologies/2010/6/Ontology1278505688859.owl#\"\n"
            + "     xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
            + "     xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
            + "     xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">\n"
            + "    <owl:Ontology rdf:about=\"\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"#hasP\"/>\n"
            + "    <owl:Class rdf:about=\"#A\"><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"#hasP\"/><owl:someValuesFrom rdf:resource=\"#P_Range\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"#A_A\"/>\n"
            + "    <owl:Class rdf:about=\"#A_B\"><rdfs:subClassOf rdf:resource=\"#A_A\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"#hasP\"/><owl:someValuesFrom rdf:resource=\"#B_P_Range\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"#A_C\"><rdfs:subClassOf rdf:resource=\"#A_A\"/></owl:Class>\n"
            + "    <owl:Class rdf:about=\"#A_D\"><rdfs:subClassOf rdf:resource=\"#A_A\"/></owl:Class>\n"
            + "    <owl:Class rdf:about=\"#B\"><rdfs:label>B</rdfs:label><rdfs:subClassOf rdf:resource=\"#A\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"#hasP\"/><owl:someValuesFrom rdf:resource=\"#B_P_Range\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"#B_P_Range\"><rdfs:subClassOf rdf:resource=\"#P_Range\"/></owl:Class>\n"
            + "    <owl:Class rdf:about=\"#C\"><rdfs:label>C</rdfs:label><rdfs:subClassOf rdf:resource=\"#A\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"#hasP\"/><owl:someValuesFrom rdf:resource=\"#C_P_Range\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"#C_P_Range\"><rdfs:subClassOf rdf:resource=\"#P_Range\"/></owl:Class>\n"
            + "    <owl:Class rdf:about=\"#D\"><rdfs:subClassOf rdf:resource=\"#A\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"#hasP\"/><owl:someValuesFrom rdf:resource=\"#D_P_Range\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"#D_P_Range\"><rdfs:subClassOf rdf:resource=\"#P_Range\"/></owl:Class>\n"
            + "    <owl:Class rdf:about=\"#P_Range\"/></rdf:RDF>";
    private static final String syntax_owl = "<?xml version=\"1.0\"?>\n"
            + "<!DOCTYPE rdf:RDF [\n"
            + "    <!ENTITY owl \"http://www.w3.org/2002/07/owl#\" >\n"
            + "    <!ENTITY xsd \"http://www.w3.org/2001/XMLSchema#\" >\n"
            + "    <!ENTITY owl2xml \"http://www.w3.org/2006/12/owl2-xml#\" >\n"
            + "    <!ENTITY rdfs \"http://www.w3.org/2000/01/rdf-schema#\" >\n"
            + "    <!ENTITY rdf \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" >\n"
            + "    <!ENTITY syntaxTest \"http://www.coode.org/oppl/ontologies/syntaxTest.owl#\" >\n"
            + "]>\n"
            + "<rdf:RDF xmlns=\"http://www.coode.org/oppl/ontologies/syntaxTest.owl#\"\n"
            + "     xml:base=\"http://www.coode.org/oppl/ontologies/syntaxTest.owl\"\n"
            + "     xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
            + "     xmlns:owl2xml=\"http://www.w3.org/2006/12/owl2-xml#\"\n"
            + "     xmlns:syntaxTest=\"http://www.coode.org/oppl/ontologies/syntaxTest.owl#\"\n"
            + "     xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
            + "     xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
            + "     xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">\n"
            + "    <owl:Ontology rdf:about=\"\"/>\n"
            + "    <owl:DatatypeProperty rdf:about=\"#aDataProperty\">\n"
            + "        <rdfs:label>aDataProperty</rdfs:label>\n"
            + "        <rdfs:range rdf:resource=\"&xsd;int\"/>\n"
            + "    </owl:DatatypeProperty>\n" + "</rdf:RDF>";
    private static final String testLongLabels_owl = "<?xml version=\"1.0\"?>\n"
            + "<!DOCTYPE rdf:RDF [\n"
            + "    <!ENTITY owl \"http://www.w3.org/2002/07/owl#\" >\n"
            + "    <!ENTITY xsd \"http://www.w3.org/2001/XMLSchema#\" >\n"
            + "    <!ENTITY owl2xml \"http://www.w3.org/2006/12/owl2-xml#\" >\n"
            + "    <!ENTITY rdfs \"http://www.w3.org/2000/01/rdf-schema#\" >\n"
            + "    <!ENTITY testLongLabels \"http://www.coode.org/oppl/testLongLabels#\" >\n"
            + "    <!ENTITY rdf \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" >\n"
            + "]>\n"
            + "<rdf:RDF xmlns=\"http://www.coode.org/oppl/testLongLabels#\"\n"
            + "     xml:base=\"http://www.coode.org/oppl/testLongLabels\"\n"
            + "     xmlns:owl2xml=\"http://www.w3.org/2006/12/owl2-xml#\"\n"
            + "     xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
            + "     xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
            + "     xmlns:testLongLabels=\"http://www.coode.org/oppl/testLongLabels#\"\n"
            + "     xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
            + "     xmlns:owl=\"http://www.w3.org/2002/07/owl#\">\n"
            + "    <owl:Ontology rdf:about=\"\"/>\n"
            + "    <owl:Class rdf:about=\"#A\"><rdfs:label>Structure of femoral artery (body structure)</rdfs:label></owl:Class>\n"
            + "    <owl:Class rdf:about=\"#B\"><rdfs:label>Structure of arm artery (body structure)</rdfs:label></owl:Class></rdf:RDF>";
    private static final String siblings_owl = "<?xml version=\"1.0\"?>\n"
            + "<!DOCTYPE rdf:RDF [\n"
            + "    <!ENTITY owl \"http://www.w3.org/2002/07/owl#\" >\n"
            + "    <!ENTITY xsd \"http://www.w3.org/2001/XMLSchema#\" >\n"
            + "    <!ENTITY rdfs \"http://www.w3.org/2000/01/rdf-schema#\" >\n"
            + "    <!ENTITY rdf \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" >\n"
            + "    <!ENTITY siblings \"http://www.semanticweb.org/ontologies/2011/1/siblings.owl#\" >\n"
            + "]>\n"
            + "<rdf:RDF xmlns=\"http://www.semanticweb.org/ontologies/2011/1/siblings.owl#\"\n"
            + "     xml:base=\"http://www.semanticweb.org/ontologies/2011/1/siblings.owl\"\n"
            + "     xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
            + "     xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
            + "     xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
            + "     xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
            + "     xmlns:siblings=\"http://www.semanticweb.org/ontologies/2011/1/siblings.owl#\">\n"
            + "    <owl:Ontology rdf:about=\"http://www.semanticweb.org/ontologies/2011/1/siblings.owl\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&siblings;hasSibling\"/>\n"
            + "    <owl:NamedIndividual rdf:about=\"&siblings;Robert\"/>\n"
            + "</rdf:RDF>";
    private static final String ondrejtest_owl = "<?xml version=\"1.0\"?>\n"
            + "<!DOCTYPE Ontology [\n"
            + "   <!ENTITY owl \"http://www.w3.org/2002/07/owl#\" >\n"
            + "   <!ENTITY xsd \"http://www.w3.org/2001/XMLSchema#\" >\n"
            + "   <!ENTITY owl2xml \"http://www.w3.org/2006/12/owl2-xml#\" >\n"
            + "   <!ENTITY rdfs \"http://www.w3.org/2000/01/rdf-schema#\" >\n"
            + "   <!ENTITY rdf \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" >\n"
            + "   <!ENTITY Ontology1269524218581 \"http://www.semanticweb.org/ontologies/2010/2/Ontology1269524218581.owl#\" >\n"
            + "]>\n"
            + "<Ontology xmlns=\"http://www.w3.org/2006/12/owl2-xml#\"\n"
            + "    xml:base=\"http://www.w3.org/2006/12/owl2-xml#\"\n"
            + "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
            + "    xmlns:owl2xml=\"http://www.w3.org/2006/12/owl2-xml#\"\n"
            + "    xmlns:Ontology1269524218581=\"http://www.semanticweb.org/ontologies/2010/2/Ontology1269524218581.owl#\"\n"
            + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
            + "    xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
            + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
            + "    URI=\"http://www.semanticweb.org/ontologies/2010/2/Ontology1269524218581.owl\">\n"
            + "   <EquivalentClasses>\n"
            + "       <Class URI=\"&Ontology1269524218581;A\"/>\n"
            + "       <ObjectSomeValuesFrom><ObjectProperty URI=\"&Ontology1269524218581;p\"/><Class URI=\"&Ontology1269524218581;C\"/></ObjectSomeValuesFrom>\n"
            + "   </EquivalentClasses>\n"
            + "   <Declaration><Class URI=\"&Ontology1269524218581;A\"/></Declaration>\n"
            + "   <SubClassOf><Class URI=\"&Ontology1269524218581;C\"/><Class URI=\"&owl;Thing\"/></SubClassOf>\n"
            + "   <Declaration><Class URI=\"&Ontology1269524218581;C\"/></Declaration>\n"
            + "   <Declaration><ObjectProperty URI=\"&Ontology1269524218581;p\"/></Declaration>\n"
            + "</Ontology>";
    private static final String sequentialUnion_owl = "<?xml version=\"1.0\"?>\n"
            + "<!DOCTYPE rdf:RDF [\n"
            + "    <!ENTITY owl \"http://www.w3.org/2002/07/owl#\" >\n"
            + "    <!ENTITY xsd \"http://www.w3.org/2001/XMLSchema#\" >\n"
            + "    <!ENTITY owl2xml \"http://www.w3.org/2006/12/owl2-xml#\" >\n"
            + "    <!ENTITY mergedont \"http://www.semanticweb.com/mergedont#\" >\n"
            + "    <!ENTITY rdfs \"http://www.w3.org/2000/01/rdf-schema#\" >\n"
            + "    <!ENTITY rdf \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" >\n"
            + "    <!ENTITY temp \"file:/C:/Tools/Alignement/align-4.0/temp.owl#\" >\n"
            + "    <!ENTITY DPWSWriter \"http://www.francetelecom.com/OWLWriter/DPWSWriter.owl#\" >\n"
            + "    <!ENTITY UPnPWriter \"http://www.francetelecom.com/OWLWriter/UPnPWriter.owl#\" >\n"
            + "]>\n"
            + "<rdf:RDF xmlns=\"http://www.semanticweb.com/mergedont#\"\n"
            + "     xml:base=\"http://www.semanticweb.com/mergedont\"\n"
            + "     xmlns:mergedont=\"http://www.semanticweb.com/mergedont#\"\n"
            + "     xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
            + "     xmlns:owl2xml=\"http://www.w3.org/2006/12/owl2-xml#\"\n"
            + "     xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
            + "     xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
            + "     xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
            + "     xmlns:temp=\"file:/C:/Tools/Alignement/align-4.0/temp.owl#\"\n"
            + "     xmlns:UPnPWriter=\"http://www.francetelecom.com/OWLWriter/UPnPWriter.owl#\"\n"
            + "     xmlns:DPWSWriter=\"http://www.francetelecom.com/OWLWriter/DPWSWriter.owl#\">\n"
            + "    <owl:Ontology rdf:about=\"http://www.semanticweb.com/mergedont\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&temp;Sequential_Union_Mapping_First_member\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&temp;Sequential_Union_Mapping_Second_member\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&temp;Simple_Mapping_Input\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&temp;Simple_Mapping_Input_Output\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&temp;Simple_Mapping_Output\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&temp;Union_Mapping\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&temp;Union_Mapping_First_member\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&temp;Union_Mapping_Second_member\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&DPWSWriter;has_DPWS_Action\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&DPWSWriter;has_DPWS_Input\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&DPWSWriter;has_DPWS_Output\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&DPWSWriter;has_DPWS_Service\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&DPWSWriter;has_DPWS_StateVariable\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&UPnPWriter;UPnP_is_instance_of_type\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&UPnPWriter;has_UPnP_Action\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&UPnPWriter;has_UPnP_Input\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&UPnPWriter;has_UPnP_Instance_Input\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&UPnPWriter;has_UPnP_Instance_Output\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&UPnPWriter;has_UPnP_Output\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&UPnPWriter;has_UPnP_Service\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&mergedont;Exact_Input_Match\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&mergedont;Exact_Input_Output_Match\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&mergedont;Exact_Output_Match\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&mergedont;PlugIn_Input_Match\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&mergedont;PlugIn_Input_Output_Match\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&mergedont;PlugIn_Output_Match\"/>\n"
            + "    <owl:ObjectProperty rdf:about=\"&mergedont;has_Next\"/>\n"
            + "    <owl:DatatypeProperty rdf:about=\"&DPWSWriter;a_has_DPWS_StateVariable_Type\"/>\n"
            + "    <owl:DatatypeProperty rdf:about=\"&DPWSWriter;has_DPWS_Logical_Device_Name\"/>\n"
            + "    <owl:DatatypeProperty rdf:about=\"&DPWSWriter;x_has_DPWS_StateVariable_Type\"/>\n"
            + "    <owl:DatatypeProperty rdf:about=\"&DPWSWriter;y_has_DPWS_StateVariable_Type\"/>\n"
            + "    <owl:DatatypeProperty rdf:about=\"&UPnPWriter;has_UPnP_Device_Type\"/>\n"
            + "    <owl:DatatypeProperty rdf:about=\"&UPnPWriter;has_UPnP_Service_ID\"/>\n"
            + "    <owl:DatatypeProperty rdf:about=\"&UPnPWriter;has_UPnP_Service_Type\"/>\n"
            + "    <owl:DatatypeProperty rdf:about=\"&UPnPWriter;has_UPnP_Service_Version\"/>\n"
            + "    <owl:DatatypeProperty rdf:about=\"&UPnPWriter;x_has_UPnP_StateVariable_Type\"/>\n"
            + "    <owl:DatatypeProperty rdf:about=\"&UPnPWriter;y_has_UPnP_StateVariable_Type\"/>\n"
            + "    <owl:Class rdf:about=\"&DPWSWriter;DPWS_Action\"><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&DPWSWriter;has_DPWS_StateVariable\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;DPWS_StateVariable\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&DPWSWriter;DPWS_Device\"><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&DPWSWriter;has_DPWS_Service\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;DPWS_Service\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&DPWSWriter;DPWS_Service\"><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&DPWSWriter;has_DPWS_Action\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;DPWS_Action\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&DPWSWriter;DPWS_StateVariable\"/>\n"
            + "    <owl:Class rdf:about=\"&DPWSWriter;DummyOperation\"><rdfs:subClassOf rdf:resource=\"&DPWSWriter;DPWS_Action\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&DPWSWriter;has_DPWS_Input\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;y\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&DPWSWriter;SeqClockStd\"><owl:equivalentClass rdf:resource=\"&UPnPWriter;Time\"/><rdfs:subClassOf rdf:resource=\"&DPWSWriter;DPWS_Service\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&DPWSWriter;has_DPWS_Action\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;Set1\"/></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&DPWSWriter;has_DPWS_Action\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;Set2\"/></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&DPWSWriter;has_DPWS_Action\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;DummyOperation\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&DPWSWriter;Set1\"><owl:equivalentClass rdf:resource=\"&UPnPWriter;Set12\"/><rdfs:subClassOf rdf:resource=\"&DPWSWriter;DPWS_Action\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&mergedont;Exact_Input_Match\"/><owl:someValuesFrom rdf:resource=\"&UPnPWriter;Set12\"/></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&DPWSWriter;has_DPWS_Input\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;x\"/></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&DPWSWriter;has_DPWS_Output\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;a\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&DPWSWriter;Set2\"><owl:equivalentClass rdf:resource=\"&UPnPWriter;Set12\"/><rdfs:subClassOf rdf:resource=\"&DPWSWriter;DPWS_Action\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&DPWSWriter;has_DPWS_Input\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;a\"/></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&DPWSWriter;has_DPWS_Output\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;y\"/></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&mergedont;Exact_Output_Match\"/><owl:someValuesFrom rdf:resource=\"&UPnPWriter;Set12\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&DPWSWriter;a\"><rdfs:subClassOf rdf:resource=\"&DPWSWriter;DPWS_StateVariable\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&DPWSWriter;a_has_DPWS_StateVariable_Type\"/><owl:someValuesFrom rdf:resource=\"&xsd;string\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&DPWSWriter;seqentialClock\"><owl:equivalentClass rdf:resource=\"&UPnPWriter;SequentialUnionClock\"/><rdfs:subClassOf rdf:resource=\"&DPWSWriter;DPWS_Device\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&DPWSWriter;has_DPWS_Logical_Device_Name\"/><owl:hasValue>hosted:seqentialClock</owl:hasValue></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&DPWSWriter;has_DPWS_Service\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;SeqClockStd\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&DPWSWriter;x\"><owl:equivalentClass rdf:resource=\"&UPnPWriter;x\"/><rdfs:subClassOf rdf:resource=\"&DPWSWriter;DPWS_StateVariable\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&DPWSWriter;x_has_DPWS_StateVariable_Type\"/><owl:someValuesFrom rdf:resource=\"&xsd;string\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&DPWSWriter;y\"><owl:equivalentClass rdf:resource=\"&UPnPWriter;y\"/><rdfs:subClassOf rdf:resource=\"&DPWSWriter;DPWS_StateVariable\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&DPWSWriter;y_has_DPWS_StateVariable_Type\"/><owl:someValuesFrom rdf:resource=\"&xsd;string\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&UPnPWriter;Newx\"><rdfs:subClassOf rdf:resource=\"&UPnPWriter;x\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;UPnP_is_instance_of_type\"/><owl:someValuesFrom rdf:resource=\"&UPnPWriter;x\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&UPnPWriter;Newy\"><rdfs:subClassOf rdf:resource=\"&UPnPWriter;y\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;UPnP_is_instance_of_type\"/><owl:someValuesFrom rdf:resource=\"&UPnPWriter;y\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&UPnPWriter;SequentialUnionClock\"><rdfs:subClassOf rdf:resource=\"&UPnPWriter;UPnP_Device\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;has_UPnP_Service\"/><owl:someValuesFrom rdf:resource=\"&UPnPWriter;Time\"/></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;has_UPnP_Device_Type\"/><owl:hasValue>urn:schemas-upnp-org:device:SequentialUnionClock:1</owl:hasValue></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&UPnPWriter;Set12\"><rdfs:subClassOf rdf:resource=\"&UPnPWriter;UPnP_Action\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&temp;Simple_Mapping_Output\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;Set2\"/></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&mergedont;Exact_Input_Match\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;Set1\"/></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&temp;Union_Mapping\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;Set1\"/></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&temp;Simple_Mapping_Input\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;Set1\"/></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;has_UPnP_Instance_Input\"/><owl:someValuesFrom rdf:resource=\"&UPnPWriter;Newx\"/></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;has_UPnP_Instance_Output\"/><owl:someValuesFrom rdf:resource=\"&UPnPWriter;Newy\"/></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;has_UPnP_Output\"/><owl:someValuesFrom rdf:resource=\"&UPnPWriter;y\"/></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&mergedont;Exact_Output_Match\"/><owl:someValuesFrom rdf:resource=\"&DPWSWriter;Set2\"/></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;has_UPnP_Input\"/><owl:someValuesFrom rdf:resource=\"&UPnPWriter;x\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&UPnPWriter;Time\"><rdfs:subClassOf rdf:resource=\"&UPnPWriter;UPnP_Service\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;has_UPnP_Service_Version\"/><owl:hasValue>1</owl:hasValue></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;has_UPnP_Service_Type\"/><owl:hasValue>urn:schemas-upnp-org:service:Time:1</owl:hasValue></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;has_UPnP_Service_ID\"/><owl:hasValue>urn:upnp-org:serviceId:Time.1</owl:hasValue></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;has_UPnP_Action\"/><owl:someValuesFrom rdf:resource=\"&UPnPWriter;Set12\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&UPnPWriter;UPnP_Action\"><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;has_UPnP_Input\"/><owl:someValuesFrom rdf:resource=\"&UPnPWriter;UPnP_StateVariable\"/></owl:Restriction></rdfs:subClassOf><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;has_UPnP_Output\"/><owl:someValuesFrom rdf:resource=\"&UPnPWriter;UPnP_StateVariable\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&UPnPWriter;UPnP_Device\"><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;has_UPnP_Service\"/><owl:someValuesFrom rdf:resource=\"&UPnPWriter;UPnP_Service\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&UPnPWriter;UPnP_Service\"><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;has_UPnP_Action\"/><owl:someValuesFrom rdf:resource=\"&UPnPWriter;UPnP_Action\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&UPnPWriter;UPnP_StateVariable\"/>\n"
            + "    <owl:Class rdf:about=\"&UPnPWriter;x\"><rdfs:subClassOf rdf:resource=\"&UPnPWriter;UPnP_StateVariable\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;x_has_UPnP_StateVariable_Type\"/><owl:someValuesFrom rdf:resource=\"&xsd;string\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "    <owl:Class rdf:about=\"&UPnPWriter;y\"><rdfs:subClassOf rdf:resource=\"&UPnPWriter;UPnP_StateVariable\"/><rdfs:subClassOf><owl:Restriction><owl:onProperty rdf:resource=\"&UPnPWriter;y_has_UPnP_StateVariable_Type\"/><owl:someValuesFrom rdf:resource=\"&xsd;string\"/></owl:Restriction></rdfs:subClassOf></owl:Class>\n"
            + "</rdf:RDF>";
    public OWLOntology test;
    public OWLOntology naf;
    public OWLOntology pizza;
    public OWLOntology syntax;
    public OWLOntology siblings;
    public OWLOntology ondrejtest;
    public OWLOntology testLongLabels;
    public OWLOntology sequentialUnion;
    public OWLOntologyManager manager;

    public Ontologies() {
        try {
            manager = OWLManager.createOWLOntologyManager();
            naf = manager.loadOntologyFromOntologyDocument(new StringDocumentSource(
                    naf_owl));
            test = manager.loadOntologyFromOntologyDocument(new StringDocumentSource(
                    test_owl));
            pizza = manager.loadOntologyFromOntologyDocument(getClass()
                    .getResourceAsStream("/pizza.owl"));
            syntax = manager.loadOntologyFromOntologyDocument(new StringDocumentSource(
                    syntax_owl));
            testLongLabels = manager
                    .loadOntologyFromOntologyDocument(new StringDocumentSource(
                            testLongLabels_owl));
            siblings = manager.loadOntologyFromOntologyDocument(new StringDocumentSource(
                    siblings_owl));
            ondrejtest = manager
                    .loadOntologyFromOntologyDocument(new StringDocumentSource(
                            ondrejtest_owl));
            sequentialUnion = manager
                    .loadOntologyFromOntologyDocument(new StringDocumentSource(
                            sequentialUnion_owl));
        } catch (OWLOntologyCreationException e) {
            throw new RuntimeException(e);
        }
    }
}
